# tools/generate_known_tables.jl
#
# W.7.1 -- generates src/known_tables.jl from handoff/x13-saveable-tables.md,
# the committed, source-cited catalogue of all X-13ARIMA-SEATS `save` table
# keywords. Run this whenever that reference file changes; never hand-edit
# src/known_tables.jl or hand-type a table list -- the whole point of this
# generator is that a 281-entry list transcribed from memory WILL contain
# errors (W.7's own handoff flags this as the mistake an earlier gap
# analysis already made once).
#
# Each catalogue row has the form:
#   | `block.longname` | `.ext` | description |
# `block` is unambiguous per row (unlike the `### heading`, which this
# script does not rely on). Where the same `ext` appears under more than
# one block (`.b1`: series vs composite; `.tac`: x11 vs seats), the FIRST
# block encountered in document order wins -- the catalogue's own document
# order already places the block this package actually supports (series,
# x11) ahead of the one it doesn't (composite) or the one that's spec.seats-
# gated anyway (seats), so first-wins is the correct tiebreak, not an
# arbitrary one.

const ROOT = normpath(joinpath(@__DIR__, ".."))
const SRC_MD = joinpath(ROOT, "handoff", "x13-saveable-tables.md")
const OUT_JL = joinpath(ROOT, "src", "known_tables.jl")

const ROW_RE = r"^\|\s*`([a-z0-9]+)\.([a-z0-9]+)`\s*\|\s*`\.([a-z0-9]+)`\s*\|"

function main()
    table_block = Dict{Symbol,String}()
    order = Symbol[]
    for line in eachline(SRC_MD)
        m = match(ROW_RE, line)
        m === nothing && continue
        blockname, _longname, ext = m.captures
        sym = Symbol(ext)
        if !haskey(table_block, sym)
            table_block[sym] = blockname
            push!(order, sym)
        end
    end

    isempty(table_block) && error("generate_known_tables: matched zero rows in $SRC_MD -- regex or file path is stale")

    io = IOBuffer()
    println(io, "# src/known_tables.jl")
    println(io, "#")
    println(io, "# AUTO-GENERATED by tools/generate_known_tables.jl from")
    println(io, "# handoff/x13-saveable-tables.md. Do not hand-edit -- rerun the")
    println(io, "# generator if the reference catalogue changes. See that tool's")
    println(io, "# own header for the tiebreak rule on the handful of `ext` values")
    println(io, "# that appear under more than one X-13 spec block.")
    println(io)
    println(io, "# Every X-13ARIMA-SEATS `save` table keyword (281 at generation time,")
    println(io, "# cross-compiled in handoff/x13-saveable-tables.md from `seasonal`'s")
    println(io, "# SPECS.csv/series.R and the Census Reference Manual), mapped to the")
    println(io, "# spec block that owns it -- e.g. :hol => \"regression\" (the file")
    println(io, "# extension is NOT the X-11 table number; A7 is saved via")
    println(io, "# `regression { save = (hol) }`, not `save = (a7)`). render()'s")
    println(io, "# per-block save-routing and series()'s table whitelist both key off")
    println(io, "# this one table.")
    println(io, "const _TABLE_BLOCK = Dict{Symbol,String}(")
    for sym in order
        println(io, "    :$(sym) => \"$(table_block[sym])\",")
    end
    println(io, ")")
    println(io)
    println(io, "# series()'s pre-subprocess whitelist -- kept as a derived Set so the")
    println(io, "# two can never drift apart.")
    println(io, "const _KNOWN_TABLES = Set{Symbol}(keys(_TABLE_BLOCK))")
    println(io)
    println(io, "# Spec blocks this package's render() already gives a typed field")
    println(io, "# (series/regression/estimate/x11/seats/outlier) OR that need the")
    println(io, "# distinct 3-column Pos/Frequency/Value parser (spectrum) rather than")
    println(io, "# the plain 2-column series() format -- both drive special-cased")
    println(io, "# behaviour in api.jl/spec.jl rather than the generic spec_args merge")
    println(io, "# path used for every other block (forecast, check, force,")
    println(io, "# slidingspans, history, identify, x11regression). composite has no")
    println(io, "# typed OR generic path -- this package has no multi-series")
    println(io, "# aggregation support at all, so a composite-only table stays")
    println(io, "# reachable in _KNOWN_TABLES (matches the catalogue) but render()")
    println(io, "# cannot actually route a save request to it.")
    println(io, "const _SPECTRUM_FORMAT_BLOCK = \"spectrum\"")

    write(OUT_JL, String(take!(io)))
    n = length(table_block)
    println("Wrote $OUT_JL with $n table entries ($(length(order)) rows deduplicated by ext).")
end

main()
