# docs/pages.jl -- the Documenter `pages` tree, factored out of make.jl so
# local/scratch build scripts can `include` the real, current list instead
# of carrying their own copy that silently goes stale as chapters are added.

const PAGES = [
    "Home" => "index.md",
    "Getting Started" => [
        "getting-started/01-installation.md",
        "getting-started/02-first-adjustment.md",
        "getting-started/03-was-it-any-good.md",
        "getting-started/04-beyond-defaults.md",
        "getting-started/05-where-next.md",
    ],
    "Manual" => [
        "manual/01-specifications.md",
        "manual/02-output-tables.md",
        "manual/03-batch-processing.md",
        "manual/04-coming-from-r-python.md",
        "manual/05-calendars-regressors.md",
        "manual/06-plots.md",
        "manual/07-datasets.md",
        "manual/08-reproducibility.md",
        "manual/09-running-x13-directly.md",
        "manual/10-diagnostics-access.md",
    ],
    "Introduction to Seasonal Adjustment" => [
        "introduction/01-why-adjust.md",
        "introduction/02-decomposition.md",
        "introduction/03-origins.md",
        "introduction/04-x11-by-hand.md",
        "introduction/05-trend-filters.md",
        "introduction/06-seasonal-filters.md",
        "introduction/07-bcd-tables.md",
        "introduction/08-extreme-values-modes.md",
        "introduction/09-end-of-series.md",
        "introduction/10-trading-day.md",
        "introduction/11-moving-holidays.md",
        "introduction/12-outliers.md",
        "introduction/13-model-selection.md",
        "introduction/14-decomposing-a-model.md",
        "introduction/15-x11-vs-seats.md",
        "introduction/16-why-so-many-diagnostics.md",
        "introduction/17-m-statistics.md",
        "introduction/18-residual-seasonality.md",
        "introduction/19-model-adequacy.md",
        "introduction/20-stability-revisions.md",
        "introduction/A-checklist.md",
        "introduction/B-further-reading.md",
    ],
    "API Reference" => "api.md",
]
